config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]

 
  get 'mercari/index' => 'mercari#index'
  get 'mercari/link' => 'mercari#link'
  resources :items do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy, :edit, :update]
    post :upload_image, on: :collection
  end
   root 'mercari#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :user 

    def self.ransackable_attributes(auth_object = nil)
        ["about", "created_at", "id", "id_value", "price", "title", "updated_at", "user_id"]
      end

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  mount_uploader :image, ImageUploader
  has_many_attached :images
  has_many :item_tag_relations, dependent: :destroy
  has_many :tags, through: :item_tag_relations, dependent: :destroy

  validates :title, presence: true
end

app/models/item_tag_relation.rb
class ItemTagRelation < ApplicationRecord
  belongs_to :item
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :item
  belongs_to :user

  validates_uniqueness_of :item_id, scope: :user_id

end

app/models/tag.rb
class Tag < ApplicationRecord

    validates :name, presence: true
  has_many :item_tag_relations, dependent: :destroy
  has_many :items, through: :item_tag_relations, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :items, dependent: :destroy
        
         has_many :likes, dependent: :destroy
         has_many :liked_items, through: :likes, source: :item
        
         def already_liked?(item)
          self.likes.exists?(item_id: item.id)
        end
        
        has_many :comments, dependent: :destroy

        has_many :items, dependent: :destroy 
        validates :name, presence: true
        validates :profile, length: { maximum: 200 }


        has_many_attached :images
        end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
        before_action :authenticate_user!
      
        def create
          item = Item.find(params[:item_id])
          comment = item.comments.build(comment_params) #buildを使い、contentとtweet_idの二つを同時に代入
         comment.user_id = current_user.id
          if comment.save
            flash[:success] = "コメントしました"
            redirect_back(fallback_location: root_path) #直前のページにリダイレクト
          else
            flash[:success] = "コメントできませんでした"
            redirect_back(fallback_location: root_path) #直前のページにリダイレクト
          end
        end
      
        def edit
          @item = Item.find(params[:item_id])
          @comment = @item.comments.find(params[:id])
        end
      
        def update
          comment = Comment.find(params[:id])
          @item = comment.item
          if comment.update(comment_params)
            redirect_to @item
          else
            redirect_to :action => "edit"
          end
        end


        def destroy
          @item = Item.find(params[:item_id])
          comment = @item.comments.find(params[:id])
          comment.destroy
          redirect_back(fallback_location: item_path)
        end

        private
      
          def comment_params
            params.require(:comment).permit(:content)
          end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

    def index
        @items = Item.all
        @q = Item.ransack(params[:q]) 
        @items= @q.result
        @users = User.all
        if params[:tag]
          Tag.create(name: params[:tag])
        end
    end

    def new
        @item = Item.new
    end

    def create
        item = Item.new(item_params)

        item.user_id = current_user.id 

        if item.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end


      def show
        @item = Item.find(params[:id])
        @comments = @item.comments
        @comment = Comment.new
      end

      def edit
        @item = Item.find(params[:id])
      end
    
      def update
        item = Item.find(params[:id])
        if item.update(item_params)
          redirect_to :action => "show", :id => item.id
        else
          redirect_to :action => "new"
        end
      end


      def destroy
        item = Item.find(params[:id])
        item.destroy
        redirect_to action: :index
      end
      

      def upload_image
        @image_blob = create_blob(params[:image])
      end


      private
      def set_item
        @item = Item.find(params[:id])
      end


      def item_params
        params.require(:item).permit(:price, :about, :title, tag_ids: []).merge(images: uploaded_images)
      end

      def uploaded_images
        params[:item][:images].drop(1).map{|id| ActiveStorage::Blob.find(id)} if params[:post][:images]
      end

      def create_blob(file)
        ActiveStorage::Blob.create_and_upload!(
          io: file.open,
          filename: file.original_filename,
          content_type: file.content_type
        )
      end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        like = current_user.likes.create(item_id: params[:item_id]) 
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(item_id: params[:item_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end

end

app/controllers/mercari_controller.rb
class MercariController < ApplicationController

    def index
    end

    def link
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/mercari_helper.rb
module MercariHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<h2>コメント編集</h2>
<%= form_for(@comment, url: item_comment_path(@comment)) do |f| %>
    <%= f.label :content %>
    <%= f.text_field :content, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>
  

app/views/items/edit.html.erb
<%= form_for @item do |f| %>

    <%= f.label :値段 %>
    <%= f.number_field :price, :size => 10 %>

    <%= f.label :商品説明  %>
    <%= f.text_area :about, :size => "30x2" %>

    <%= f.label :商品タイトル%>
    <%= f.text_field :title, :size => 30 %>



    <%= form_with(model: @item, local: true, data: { controller: "images"}) do |f| %>

 

  <div class="mb-3">
    <%= f.label :title, "タイトル", class: "font-semibold block p-1" %>
    <%= f.text_field :title, autofocus: true, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div class="mb-3">
    <%= f.label :images, "画像", class: "font-semibold block p-1" %>
    <%= f.file_field :images, multiple: true, accept: "image/jpeg,image/gif,image/png", data: { images_target: "select", action: "change->images#selectImages" } %>
  </div>
  <div data-images-target="preview">
    <% if @item.images.attached? %>
      <% @item.images.each do |image| %>
        <div class="image-box inline-flex mx-1 mb-5" data-controller="images" data-images-target= "image_box">
          <div class="text-center">
            <%= image_tag image, width: "100" %>
            <a class="link cursor-pointer" data-action="click->images#deleteImage">削除</a>
            <%= f.hidden_field :images, name: "item[images][]", style: "display: none", value: "#{image.blob.id}" %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="mb-3">
    <%= f.submit  "投稿する", class: "btn btn-sky" %>
  </div>
<% end %>

<%= form_for(@comment, url: item_comment_path(@comment)) do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content, :size => 140 %> 
  <%= f.submit "編集する" %>
<% end %>

  
    <%= f.submit "編集する" %>
  <% end %>

app/views/items/index.html.erb
<%= link_to "新規投稿ページへ", new_item_path %>

<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>

<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>


<%= form_tag({controller:"items",action:"index"}, method: :get) do %>
    <%= text_field_tag :tag %>
    <%= submit_tag 'タグを追加' %>
<% end %>


<%= search_form_for @q  do |f| %>
   <%= f.label :title, '商品名' %>
  <%= f.search_field :title_cont %>
  
  <%= f.label :price_cont, '値段' %>
  <%= f.search_field :price_cont %>

   <%= f.label :about_cont, '説明' %>
  <%= f.search_field :about_cont %>

  <%= f.submit "search" %>

<% end %>

<div class="tweets-container">
  <% @items.each do |t| %>


    <% if user_signed_in? %>
      <% if current_user.id == t.user_id %>
      <% elsif current_user.admin? %>
        <%= link_to "管理者用編集", edit_post_path(t.id) %>
        <%= link_to "管理者用削除", item_path(t.id), method: :delete %>
      <% end %>
    <% end %>


    <div class="tweet">
      <%= t.title %>
      <%= t.price %>
      <%= t.about %>
      <%= t.created_at %>
 
  
      <div class="my-8">
      <div id="item-<%= t.id %>" class="mb-3">
        <p class="font-bold">タイトル：<%= t.title %></p>
        <% if t.images.attached? %>
          <% t.images.each do |image| %>
            <div class="mb-2 inline-flex">
              <%= image_tag(image, width:100, class: "") %>
              
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    
   

    
      <%= link_to t.user.name, user_path(t.user.id) %>
      <%= t.user.email %> 
      <%= link_to "詳細へ", item_path(t.id) %>
      <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "編集する", edit_item_path(t.id) %>
      <%= link_to "削除する", item_path(t.id), method: :delete %>
    <% end %> 
    

     <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
            <%= link_to item_like_path(id: t.id, item_id: t.id), data: { turbo_method: :delete } do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
            <% end %>
        <% else %>
            <%= link_to item_likes_path(id: t.id, item_id: t.id), data: { turbo_method: :post }  do %>
               <i class="far fa-heart"></i><%= t.likes.count %>
            <% end %>
          <% end %>
      <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
      <% end %>
   </div>
  <% end %>
</div>


<% if user_signed_in? %>
    <% if current_user.admin? %>
      <%= link_to "秘密のページへ", users_path %>
    <% end %>
<% end %>

app/views/items/new.html.erb
<h3>新規投稿</h3>
<%= form_with(model: @item, local: true, multipart: true, data: { controller: "images"}) do |f| %>

  <div class="field">
    <%= f.label :商品タイトル%>
    <%= f.text_field :title, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :値段 %>
    <%= f.number_field :price, :size => 10 %>
  </div>

  <div class="field">
    <%= f.label :商品説明  %>
    <%= f.text_area :about, :size => "30x2" %>
  </div>

  
  
    <div class="mb-3">
      <%= f.label :images, "画像", class: "font-semibold block p-1" %>
      <%= f.file_field :images, multiple: true, accept: "image/jpeg,image/gif,image/png", data: { images_target: "select", action: "change->images#selectImages" } %>
    </div>
    <div data-images-target="preview">
      <% if @item.images.attached? %>
        <% @item.images.each do |image| %>
          <div class="image-box inline-flex mx-1 mb-5" data-controller="images" data-images-target= "image_box">
            <div class="text-center">
              <%= image_tag image, width: "100" %>
              <a class="link cursor-pointer" data-action="click->images#deleteImage">削除</a>
              <%= f.hidden_field :images, name: "item[images][]", style: "display: none", value: "#{image.blob.id}" %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

  
   <div class='form-group'>
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class='form-check'>
                <%= tag.label class: 'form-check-label' do %>
                    <%= tag.check_box class: 'form-check-input' %>
                    <%= tag.text %>
                <% end %>
            </div>
        <% end %>
    </div>


  <%= f.submit "投稿する" %>
<% end %>
<%= link_to "投稿一覧に戻る", items_path %>

app/views/items/show.html.erb
<h3>投稿詳細</h3>

<div class="tweet">
  <p><%= @item.title %></p>
  <p><%= @item.price %></p>
  <p><%= @item.about %></p>
  <p><%= @item.created_at %></p>

  <% if user_signed_in? %>
      <% if current_user.already_liked?(@item) %>
        <%= link_to item_like_path(id: @item.id, item_id: @item.id), data: { turbo_method: :delete } do %>
            <i class="fas fa-heart"></i><%= @item.likes.count %>
        <% end %>
      <% else %>
        <%= link_to item_likes_path(id: @item.id, item_id: @item.id), data: { turbo_method: :post }  do %>
           <i class="far fa-heart"></i><%= @item.likes.count %>
        <% end %>
      <% end %>
  <% else %>
     <i class="far fa-heart"></i><%= @item.likes.count %>
  <% end %>

</div>
<%= link_to "編集する", edit_item_path(@item.id) %>


<% @item.tags.each do |tag| %>
    <span><%= tag.name %></span>
<% end %>


<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
      <%= button_to "削除する", item_comment_path(@item,c), method: :delete %>
      <%= link_to "編集する", edit_item_comment_path(@item,c) %>
      <% end %>



  <% if user_signed_in? %>
    <%= form_with(model: [@item, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>


<%= link_to "投稿一覧に戻る", items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mercari</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/e8681e8630.js" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/item.html.erb
 {
  white-space: pre-wrap;
}

app/views/mercari/index.html.erb
<%= link_to "ログイン", items_path %>
<%= link_to "新規登録", new_user_registration_path %>

app/views/mercari/link.html.erb
My name is Haruka Minami

app/views/users/index.html.erb
<% if user_signed_in? %>
<% if current_user.admin? %>
  <% sum = 0 %>
    <% @users.each do |u| %>
      <p>メアド:<%= u.email %></p>
      <p>名前:<%= u.name %>さん</p>
    <% sum += 1 %>
    <% end %>
  <p>登録者合計：<%= sum %></p>
 <% end %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<p>名前 : <%= @user.name %></p>
<% if @user.image.attached? %>
     <%= image_tag  @user.image, size: '250x200'%>
<% end %>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>
<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.items.each do |t| %>
  <%= t.user.name %>
  <%= t.title %>
  <%= image_tag t.image_url, size: "250x200" if t.image? %>
  <%= t.price %>
  <%= t.about %>
  <%= t.created_at %>
  <%= t.user.email %> 
<% end %>

<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_items.each do |t| %>
  <%= t.user.name %>
  <%= t.title %>
  <%= image_tag t.image_url, size: "250x200" if t.image? %>
  <%= t.price %>
  <%= t.about %>
  <%= t.created_at %>
  <%= t.user.email %> 
<% end %>

<%= link_to "投稿一覧に戻る", items_path %>